### ISSUE TITLE
UI issue with long chain names

### ISSUE THREAD

**Issue by miohtama** [antonnell/networklist-org#31]
Currently the search interface truncates the chain name, making it harder to reason about chain names and ids.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/49922/139925390-917641b8-abb2-436b-8487-17d498d060c2.png">

I would propose giving 2 lines of space for the chain name.

**Comment by Magicking** [comment]
This is a troubling issue as if we use the search of the browser is almost impossible to find which network we are looking for
![image](https://user-images.githubusercontent.com/284088/140619997-9f7bd527-0181-4937-9f61-b4e15a7955f5.png)

As you can see here even with the internal search bar it's impossible to match visually the searched theme.

The panel on the left could also be reduced a bit to make space for the letters and maybe alt-values as well so that tooltip hovering above the title can help users as well as make it more friendly for accessibility browsers.
